#!/usr/bin/env node
/**
 * Fetches every Google Sheet tab named in src/data/sheets.config.json and
 * writes it to src/data/sheets/<name>.json — the build-time half of the data
 * layer. Runs first in `npm run build`, so pages can import the JSON as if it
 * were committed content.
 *
 *   node scripts/fetch-sheets.mjs
 *
 * The config is JSON, not site.ts, because this is a plain Node script and
 * cannot import TypeScript. site.ts re-exports the same map (as SHEETS) for
 * component use, so there is still exactly one place to add a tab. The worker
 * serves the same tabs live at /api/data/<tab> for the client-side silent
 * refresh — build-time snapshot for first paint, live fetch for freshness.
 *
 * SOFT-FAIL BY DESIGN. A build must not die because Google is slow or the
 * machine is offline. On any fetch failure: if a previously fetched JSON is
 * already committed, keep it and warn (offline builds ship the last known
 * data); if none exists, write an empty rows file and warn (the page renders
 * its empty state instead of crashing the build). The only hard failure is a
 * malformed URL in the config, because that is a typo to fix, not weather.
 *
 * PRIVACY (two-tab pattern, restated from site.ts): only ever publish a
 * `public` tab that QUERY-selects the public columns of approved rows. The
 * `master` tab with emails/phones stays unpublished — then this script cannot
 * leak contact fields even by mistake, because it can never see them.
 *
 * Zero dependencies — the CSV parser below handles quoted fields, embedded
 * commas and newlines, which is all a published Google CSV emits.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = resolve(root, 'src/data/sheets');
mkdirSync(outDir, { recursive: true });

const config = JSON.parse(
  readFileSync(resolve(root, 'src/data/sheets.config.json'), 'utf8')
);
const tabs = Object.entries(config.tabs ?? {});

/**
 * RFC-4180-ish CSV: quoted fields may contain commas, newlines and doubled
 * quotes. A state machine, not a regex — a regex split breaks on the first
 * quoted comma and does so silently.
 */
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        field += c;
      }
    } else if (c === '"') {
      inQuotes = true;
    } else if (c === ',') {
      row.push(field);
      field = '';
    } else if (c === '\n' || c === '\r') {
      if (c === '\r' && text[i + 1] === '\n') i++;
      row.push(field);
      rows.push(row);
      row = [];
      field = '';
    } else {
      field += c;
    }
  }
  if (field !== '' || row.length) {
    row.push(field);
    rows.push(row);
  }
  return rows;
}

/** Header row → array of objects. Blank lines (all-empty rows) are dropped. */
function toObjects(rows) {
  if (!rows.length) return [];
  const headers = rows[0].map((h) => h.trim());
  return rows
    .slice(1)
    .filter((r) => r.some((cell) => cell.trim() !== ''))
    .map((r) => Object.fromEntries(headers.map((h, i) => [h, (r[i] ?? '').trim()])));
}

const COMMENT = 'generated by scripts/fetch-sheets.mjs — do not hand-edit';

let fetched = 0;
let kept = 0;

for (const [name, { url: sheetUrl } = {}] of tabs) {
  // A malformed URL is a config typo — fail loudly, it will never work.
  let parsed;
  try {
    parsed = new URL(sheetUrl);
  } catch {
    console.error(`fetch-sheets: tab "${name}" has a malformed url: ${JSON.stringify(sheetUrl)}`);
    process.exit(1);
  }

  const outFile = resolve(outDir, `${name}.json`);
  try {
    const res = await fetch(parsed.href, { redirect: 'follow' });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const rowsArr = toObjects(parseCsv(await res.text()));
    writeFileSync(outFile, JSON.stringify({ $comment: COMMENT, rows: rowsArr }, null, 2) + '\n');
    console.log(`fetch-sheets: ${name} — ${rowsArr.length} rows`);
    fetched += 1;
  } catch (e) {
    if (existsSync(outFile)) {
      // Offline / flaky network: the committed snapshot still builds a site.
      console.warn(`fetch-sheets: ${name} — fetch failed (${e.message}), keeping committed copy`);
      kept += 1;
    } else {
      console.warn(`fetch-sheets: ${name} — fetch failed (${e.message}), no committed copy; writing empty rows`);
      writeFileSync(outFile, JSON.stringify({ $comment: COMMENT, rows: [] }, null, 2) + '\n');
    }
  }
}

console.log(
  tabs.length
    ? `fetch-sheets: done — ${fetched} fetched, ${kept} kept from committed copies`
    : 'fetch-sheets: no tabs configured in src/data/sheets.config.json — nothing to do'
);
